import Head from 'next/head';

import '../styles/globals.css';
import 'bootstrap/dist/css/bootstrap.css';

//import { auth } from '../lib/firebase.config';


function MyApp({ Component, pageProps }) {
  console.log(auth.currentUser)
  return <>
    <div class="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Component {...pageProps} />
      </main>
    </div>
  </>;
}

export default MyApp
